apiVersion: v2
name: mlops-platform
description: MLOps Platform Helm chart
type: application
version: 2.0.0
appVersion: "2.0.0"
dependencies:
  - name: redis
    version: "18.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: mlflow
    version: "0.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mlflow.enabled
